Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/sql-server"
    config.vm.box_version = "2019.2102.2409"
  
    # Configuração de rede para permitir acesso externo ao SQL Server
    config.vm.network "forwarded_port", guest: 1433, host: 1433, auto_correct: true
  
    # Configuração de memória RAM
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end
  